In [5]:
import pandas as pd

df = pd.read_csv("Employee.csv")
df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1

In [6]:
df.columns

Index(['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender',
       'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot'],
      dtype='str')

In [7]:
df[df["PaymentTier"] == 3]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
...,...,...,...,...,...,...,...,...,...
4647,Bachelors,2016,Pune,3,30,Male,No,2,0
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [8]:
df[df["Age"] > 30]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1
9,Masters,2017,New Delhi,2,37,Male,No,2,0
...,...,...,...,...,...,...,...,...,...
4643,Bachelors,2013,Bangalore,3,31,Female,No,5,0
4644,Bachelors,2015,Pune,3,32,Female,Yes,1,1
4645,Masters,2017,Pune,2,31,Female,No,2,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [9]:
df[df["City"] == "Bangalore"]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1
10,Masters,2012,Bangalore,3,27,Male,No,5,1
...,...,...,...,...,...,...,...,...,...
4643,Bachelors,2013,Bangalore,3,31,Female,No,5,0
4646,Bachelors,2013,Bangalore,3,25,Female,No,3,0
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [10]:
df[(df["City"] == "Bangalore") & (df["PaymentTier"] == 3)]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1
10,Masters,2012,Bangalore,3,27,Male,No,5,1
...,...,...,...,...,...,...,...,...,...
4643,Bachelors,2013,Bangalore,3,31,Female,No,5,0
4646,Bachelors,2013,Bangalore,3,25,Female,No,3,0
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [11]:
df[(df["Gender"] == "Female") & (df["Age"] < 30) & (df["LeaveOrNot"] == 1)]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
1,Bachelors,2013,Pune,1,28,Female,No,3,1
19,Bachelors,2016,New Delhi,2,22,Female,No,0,1
38,Bachelors,2017,Pune,2,29,Female,No,2,1
51,Bachelors,2015,Pune,2,26,Female,No,4,1
63,Bachelors,2014,Pune,1,22,Female,No,0,1
...,...,...,...,...,...,...,...,...,...
4596,Bachelors,2018,New Delhi,3,27,Female,No,5,1
4609,Bachelors,2014,Pune,1,22,Female,No,0,1
4610,Bachelors,2015,Pune,3,24,Female,No,2,1
4612,Bachelors,2012,Bangalore,3,23,Female,No,1,1
4630,Bachelors,2012,Pune,3,25,Female,No,3,1

In [12]:
df["City"] = df["City"].str.strip()
df["Gender"] = df["Gender"].str.strip()