In [ ]:
import pandas as pd

df = pd.read_csv("Employee.csv")
df.head()import pandas as pd

df = pd.read_csv("Employee.csv")
df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Bachelors,2017,Bangalore,3,34.0,Male,No,0.0,0.0,NaN,NaN,NaN
1,Bachelors,2013,Pune,1,28.0,Female,No,3.0,1.0,NaN,NaN,NaN
2,Bachelors,2014,New Delhi,3,38.0,Female,No,2.0,0.0,NaN,NaN,NaN
3,Masters,2016,Bangalore,3,27.0,Male,No,5.0,1.0,NaN,NaN,NaN
4,Masters,2017,Pune,3,24.0,Male,Yes,2.0,1.0,NaN,NaN,NaN

In [20]:
df.columns

Index(['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender',
       'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11'],
      dtype='str')

In [21]:
df[df["PaymentTier"] == 3]

Empty DataFrame
Columns: [Education, JoiningYear, City, PaymentTier, Age, Gender, EverBenched, ExperienceInCurrentDomain, LeaveOrNot, Unnamed: 9, Unnamed: 10, Unnamed: 11]
Index: []

In [22]:
df[df["Age"] > 30]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Bachelors,2017,Bangalore,3,34.0,Male,No,0.0,0.0,NaN,NaN,NaN
2,Bachelors,2014,New Delhi,3,38.0,Female,No,2.0,0.0,NaN,NaN,NaN
6,Bachelors,2015,New Delhi,3,38.0,Male,No,0.0,0.0,NaN,NaN,NaN
7,Bachelors,2016,Bangalore,3,34.0,Female,No,2.0,1.0,NaN,NaN,NaN
9,Masters,2017,New Delhi,2,37.0,Male,No,2.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
4643,Bachelors,2013,Bangalore,3,31.0,Female,No,5.0,0.0,NaN,NaN,NaN
4644,Bachelors,2015,Pune,3,32.0,Female,Yes,1.0,1.0,NaN,NaN,NaN
4645,Masters,2017,Pune,2,31.0,Female,No,2.0,0.0,NaN,NaN,NaN
4649,Masters,2013,Pune,2,37.0,Male,No,2.0,1.0,NaN,NaN,NaN
4652,Bachelors,2015,Bangalore,3,33.0,Male,Yes,4.0,0.0,NaN,NaN,NaN

In [23]:
df[df["City"] == "Bangalore"]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Bachelors,2017,Bangalore,3,34.0,Male,No,0.0,0.0,NaN,NaN,NaN
3,Masters,2016,Bangalore,3,27.0,Male,No,5.0,1.0,NaN,NaN,NaN
5,Bachelors,2016,Bangalore,3,22.0,Male,No,0.0,0.0,NaN,NaN,NaN
7,Bachelors,2016,Bangalore,3,34.0,Female,No,2.0,1.0,NaN,NaN,NaN
10,Masters,2012,Bangalore,3,27.0,Male,No,5.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
4643,Bachelors,2013,Bangalore,3,31.0,Female,No,5.0,0.0,NaN,NaN,NaN
4646,Bachelors,2013,Bangalore,3,25.0,Female,No,3.0,0.0,NaN,NaN,NaN
4648,Bachelors,2013,Bangalore,3,26.0,Female,No,4.0,0.0,NaN,NaN,NaN
4651,Bachelors,2012,Bangalore,3,30.0,Male,Yes,2.0,0.0,NaN,NaN,NaN
4652,Bachelors,2015,Bangalore,3,33.0,Male,Yes,4.0,0.0,NaN,NaN,NaN

In [24]:
df[(df["City"] == "Bangalore") & (df["PaymentTier"] == 3)]

Empty DataFrame
Columns: [Education, JoiningYear, City, PaymentTier, Age, Gender, EverBenched, ExperienceInCurrentDomain, LeaveOrNot, Unnamed: 9, Unnamed: 10, Unnamed: 11]
Index: []

In [25]:
df[(df["Gender"] == "Female") & (df["Age"] < 30) & (df["LeaveOrNot"] == 1)]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Unnamed: 9,Unnamed: 10,Unnamed: 11
1,Bachelors,2013,Pune,1,28.0,Female,No,3.0,1.0,NaN,NaN,NaN
19,Bachelors,2016,New Delhi,2,22.0,Female,No,0.0,1.0,NaN,NaN,NaN
38,Bachelors,2017,Pune,2,29.0,Female,No,2.0,1.0,NaN,NaN,NaN
51,Bachelors,2015,Pune,2,26.0,Female,No,NaN,1.0,NaN,NaN,NaN
63,Bachelors,2014,Pune,1,22.0,Female,No,0.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
4596,Bachelors,2018,New Delhi,3,27.0,Female,No,5.0,1.0,NaN,NaN,NaN
4609,Bachelors,2014,Pune,1,22.0,Female,No,0.0,1.0,NaN,NaN,NaN
4610,Bachelors,2015,Pune,3,24.0,Female,No,2.0,1.0,NaN,NaN,NaN
4612,Bachelors,2012,Bangalore,3,23.0,Female,No,1.0,1.0,NaN,NaN,NaN
4630,Bachelors,2012,Pune,3,25.0,Female,No,3.0,1.0,NaN,NaN,NaN

In [26]:
df["City"] = df["City"].str.strip()
df["Gender"] = df["Gender"].str.strip()

In [27]:
df["City"] = df["City"].str.strip()
df["Gender"] = df["Gender"].str.strip()
df["grouph"] = df["PaymentTier"].astype(str).apply(lambda x: "Group H" if x == "3" else "Other")
df["ANALYSICS"] = pd.to_numeric(df["ExperienceInCurrentDomain"], errors="coerce").apply(
    lambda x: "Analytics" if x >= 3 else "Non-Analytics"
)

print(df[["grouph", "ANALYSICS"]].head())

    grouph      ANALYSICS
0  Group H  Non-Analytics
1    Other      Analytics
2  Group H  Non-Analytics
3  Group H      Analytics
4  Group H  Non-Analytics

In [28]:
grouped = df.groupby(["JoiningYear", "City"]).size().reset_index(name="Total_Employees")
grouped

    JoiningYear       City  Total_Employees
0          2012  Bangalore              302
1          2012  New Delhi               92
2          2012       Pune              110
3          2013  Bangalore              340
4          2013  New Delhi              149
5          2013       Pune              180
6          2014  Bangalore              387
7          2014  New Delhi              126
8          2014       Pune              186
9          2015  Bangalore              314
10         2015  New Delhi              134
11         2015       Pune              333
12         2016  Bangalore              313
13         2016  New Delhi               95
14         2016       Pune              117
15         2017  Bangalore              369
16         2017  New Delhi              474
17         2017       Pune              265
18         2018  Bangalore              203
19         2018  New Delhi               87
20         2018       Pune               77

In [29]:
left_emp = df[df["LeaveOrNot"] == 1] \
    .groupby(["JoiningYear", "City"]) \
    .size() \
    .reset_index(name="Left_Count")

left_emp

    JoiningYear       City  Left_Count
0          2012  Bangalore          49
1          2012  New Delhi          22
2          2012       Pune          38
3          2013  Bangalore          82
4          2013  New Delhi          63
5          2013       Pune          79
6          2014  Bangalore          73
7          2014  New Delhi          22
8          2014       Pune          78
9          2015  Bangalore          66
10         2015  New Delhi          31
11         2015       Pune         221
12         2016  Bangalore          56
13         2016  New Delhi          21
14         2016       Pune          40
15         2017  Bangalore          69
16         2017  New Delhi         121
17         2017       Pune         107
18         2018  Bangalore         200
19         2018  New Delhi          86
20         2018       Pune          76

In [30]:
avg_exp = df.groupby(["JoiningYear", "City"])["ExperienceInCurrentDomain"].mean().reset_index()
avg_exp

    JoiningYear       City  ExperienceInCurrentDomain
0          2012  Bangalore                   2.996689
1          2012  New Delhi                   3.054348
2          2012       Pune                   3.227273
3          2013  Bangalore                   3.026471
4          2013  New Delhi                   3.067114
5          2013       Pune                   2.833333
6          2014  Bangalore                   2.971576
7          2014  New Delhi                   2.865079
8          2014       Pune                   3.048649
9          2015  Bangalore                   2.802548
10         2015  New Delhi                   2.686567
11         2015       Pune                   2.737952
12         2016  Bangalore                   2.814103
13         2016  New Delhi                   2.831579
14         2016       Pune                   2.957265
15         2017  Bangalore                   2.926630
16         2017  New Delhi                   2.890295
17         2017       Pune                   2.849057
18         2018  Bangalore                   2.896040
19         2018  New Delhi                   2.758621
20         2018       Pune                   2.844156